<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PhoneWheel.Server.UI</RootNamespace>
    <AssemblyName>PhoneWheel.Server.UI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhoneWheel.Server\PhoneWheel.Server.csproj" />
  </ItemGroup>

</Project>